[package]
name = "write"
edition = "2021"
version.workspace = true

[dependencies]
tokio.workspace = true
axum.workspace = true
parquet.workspace = true
arrow.workspace = true
serde.workspace = true
serde_json.workspace = true
async-trait.workspace = true
thiserror.workspace = true
