[package]
name = "catalog"
edition = "2021"
version.workspace = true

[dependencies]
axum.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
thiserror.workspace = true
sqlx.workspace = true
