@hostname = http://localhost
@port = 3000
@host = {{hostname}}:{{port}}
@contentType = application/json

###

GET {{host}}/status


### 

POST {{host}}/query
Content-Type: {{contentType}}

{
    "query": "SELECT * FROM table1;"
}