[package]
name = "query"
edition = "2021"
version.workspace = true

[dependencies]
axum.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
arrow.workspace = true
arrow-json.workspace = true
thiserror.workspace = true
